"""add test designs, test cases, test case versions and test case counters

Revision ID: 5593e511c60c
Revises: da6737a9255c
Create Date: 2026-09-22 17:26:34.637181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5593e511c60c'
down_revision: Union[str, None] = 'da6737a9255c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually adjusted: `test_cases.priority` reuses the `requirement_priority`
    # Postgres ENUM type that Sprint 2's migration (5f00af1fddb3) already
    # created for `requirements.priority` (see
    # app.domains.testcases.models.TestCase.priority's docstring - "priority"
    # means the same thing everywhere in this system, so there's one shared
    # enum type, not two parallel ones). `create_type=False` tells SQLAlchemy
    # not to try to CREATE TYPE requirement_priority again here (autogenerate
    # doesn't know the type already exists and would otherwise emit a
    # `CREATE TYPE` that fails with "type already exists"); correspondingly,
    # downgrade() below must NOT drop this type, since `requirements.priority`
    # still depends on it.
    requirement_priority_enum = postgresql.ENUM(
        'low', 'medium', 'high', 'critical', name='requirement_priority', create_type=False
    )

    op.create_table('test_case_counters',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('next_value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('test_designs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'rejected', name='test_design_status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('test_design_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('positive', 'negative', 'boundary', 'edge_case', 'business_logic', 'validation', 'security', 'performance', 'regression', name='test_case_category'), nullable=False),
    sa.Column('testing_level', sa.Enum('functional', 'api', 'ui', 'integration', 'security', 'performance', 'regression', name='testing_level'), nullable=False),
    sa.Column('priority', requirement_priority_enum, nullable=False),
    sa.Column('severity', sa.Enum('minor', 'major', 'critical', 'blocker', name='test_case_severity'), nullable=False),
    sa.Column('preconditions', sa.Text(), nullable=False),
    sa.Column('test_data', sa.Text(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('business_rule', sa.Text(), nullable=False),
    sa.Column('automation_candidate', sa.Boolean(), nullable=False),
    sa.Column('execution_type', sa.Enum('manual', 'automation', 'hybrid', name='execution_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', name='test_case_status'), nullable=False),
    sa.Column('source', sa.Enum('ai', 'human', name='test_case_source'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_design_id'], ['test_designs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_test_case_project_code'),
    sa.UniqueConstraint('sequence')
    )
    op.create_table('test_case_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edited_by', sa.UUID(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_case_versions')
    op.drop_table('test_cases')
    op.drop_table('test_designs')
    op.drop_table('test_case_counters')
    # ### end Alembic commands ###
    # Manually added: op.drop_table() does not drop the PostgreSQL ENUM types
    # backing the enum-typed columns above, so a downgrade followed by
    # another upgrade would otherwise fail with "type already exists" (same
    # fix as 5f00af1fddb3's/da6737a9255c's downgrade() for their own enums).
    # Deliberately NOT dropping 'requirement_priority' here: it's a shared
    # type also backing requirements.priority (created by 5f00af1fddb3,
    # dropped by 5f00af1fddb3's own downgrade()), never created by this
    # migration's upgrade() (create_type=False above), so it isn't this
    # migration's to drop.
    sa.Enum(name='test_case_source').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='test_case_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='execution_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='test_case_severity').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='testing_level').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='test_case_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='test_design_status').drop(op.get_bind(), checkfirst=True)
